class TimeZone:
    timezone_offsets = {
        "BIT": -12,
        "NUT": -11,
        "HST": -10,
        "AKST": -9,
        "PST": -8,
        "MST": -7,
        "CST": -6,
        "EST": -5,
        "AST": -4,
        "NST": -3.5,
        "BRT": -3,
        "GST": -2,
        "AZOT": -1,
        "GMT": 0,
        "CET": 1,
        "EET": 2,
        "MSK": 3,
        "IRST": 3.5,
        "AZT": 4,
        "AFT": 4.5,
        "PKT": 5,
        "IST": 5.5,
        "NPT": 5.75,
        "BST": 6,
        "CCT": 6.5,
        "ICT": 7,
        "CST": 8,
        "JST": 9,
        "ACST": 9.5,
        "AEST": 10,
        "LHST": 10.5,
        "SBT": 11,
        "NFT": 11.5,
        "NZST": 12,
        "CHAST": 12.75,
        "TOT": 13,
        "LINT": 14,
    }

    def __init__(self, tz_name):
        self.name = tz_name
        self.offset = TimeZone.timezone_offsets[tz_name]
